# Use a Python 3.9 base image
FROM python:3.9-alpine3.19

# Set the working directory in the container
WORKDIR /app

# Copy project files to the container
COPY src/commons/ commons/
COPY src/consumer/ .

COPY requirements.txt .

RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["python", "main.py"]

# CMD ["ls", "-la"]