task_database: '..\tasks.db'

consumer_options:
  workers: 5
  worker_type: 'thread'  # or greenlet

app:
  host: 0.0.0.0
  port: 5000

log:
  rotation: '00:00'
  retention: "30 days"
  compression: 'zip'
  level: 'INFO'
  format: '<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | {thread.name} <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>'
